[workspace]
members = [
    #learn
    "learn/book",
    "learn/macro",
    "learn/daily",
    # lib
    "rexl",
    "rexl-math",
    "rexl-matrix",
    # bin
    "rexl-cli/rfind",
    "rexl-cli/rserve"
]