[package]
name = "rexl_wrap"
description = "an useful wrapper for popular crates"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
include.workspace = true

[dependencies]
tracing = "0.1.44"
tracing-appender = "0.2.4"
tracing-subscriber = {version = "0.3.22", features = ["env-filter", "registry", "fmt", "json"]}
